### ISSUE TITLE
ImportError: ED_BertForSequenceClassification in predict.py

### ISSUE THREAD

**Issue by annachernysheva179** [barthelemymp/TULIP-TCR#8]
Hi,
During the execution of predict.py I got an error in line 16 :
from src.multiTrans import ED_BertForSequenceClassification, TCRDataset, BertLastPooler...
ImportError: cannot import name 'ED_BertForSequenceClassification' from 'src.multiTrans'
And I didn't find any ED_BertForSequenceClassification in multiTrans.py.
Could you please provide support on it?

**Comment by barthelemymp** [comment]
Hi, 

Indeed I forgot to update this file.
Sorry about this, I have been changing a lot a things recently.
Should work now.
Thanks for your interest.

Best
